### ISSUE TITLE
Add note to readme that node >14.18 is required

### ISSUE THREAD

**Issue by dnchattan** [touchifyapp/node-fetch-cjs#1]
The `node:` require syntax requires node 14.18, which I found I was still on 14.15... took a little while to figure out what was going on :smile:

**Comment by SomaticIT** [comment]
Hello,

Thank you for reporting this issue.
It was a mistake, i didn't notice that this protocol was added in `node-fetch` and its dependencies.

I updated the build process to remove all `node:` occurrences.
I think you can safely use the package on any LTS version now.

A new version `3.1.0-fix.1` has been published to npm.

**Comment by dnchattan** [comment]
even better! thank you for maintaining this package
