### ISSUE TITLE
node-fetch@3.3.0 released

### ISSUE THREAD

**Issue by kamilmielnik** [touchifyapp/node-fetch-cjs#2]
[README says](https://github.com/touchifyapp/node-fetch-cjs/blob/main/README.md?plain=1#L15):

> This repository is automatically updated when a new version of node-fetch is released

`node-fetch@3.3.0` [has been released on 2022-11-10](https://github.com/node-fetch/node-fetch/releases/tag/v3.3.0), but this time Touchify Bot did not update the code.

**Comment by char0n** [comment]
Yep, 3.3.2 is already out.

**Comment by SomaticIT** [comment]
Hello,

Sorry for this.
The automatic workflow was disabled by Github...

I re-enabled it. It should start tonight.

**Comment by SomaticIT** [comment]
`node-fetch-cjs@3.3.2` released!
